### ISSUE TITLE
FEATURE: Implement vault chooser when buchhalter runs for the first time

### ISSUE THREAD

**Issue by brgmn** [buchhalter-ai/buchhalter-ai-cli#99]
At the moment we set the buchhalter vault to "Base" vault by default. But it's hard to guess for a new user and can lead to non-functional buchhalter commands. 

# Definition of done

- [ ] When starting buchhalter for the first time (no .buchhalter.yaml file) "op vault list" is executed and the user can choose the vault that should be used for buchhalter
- [ ] The choosen vault is saved in .buchhalter.yaml configuration file

**Comment by bwaidelich** [comment]
I still experience some issues with vault selection (MacBook Pro M1, Mac OS 14.6.1):

When the 1password app is not running, even trying to display the CLI version runs into a timeout:

https://github.com/user-attachments/assets/c32c4ea9-9e5f-4413-a044-d0cb39c20391

When I started the app the CLI command works (even without running `op signin` first) but only my personal account is selectable:

https://github.com/user-attachments/assets/38570fc5-3230-4083-b42e-8adeb574a1f0

**Comment by andygrunwald** [comment]
Thanks @bwaidelich.
I try to look into this in the next days!
